---
abstract: 'mruby binding for perl5.'
author:
  - 'Tokuhiro Matsuno E<lt>tokuhirom AAJKLFJEF@ GMAIL COME<gt>'
build_requires:
  Cwd::Guard: 0
  Devel::PPPort: 0
  ExtUtils::CBuilder: 0
  Test::More: 0.98
  Test::Requires: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Module::Build version 0.4, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: mRuby
no_index:
  directory:
    - inc
provides:
  mRuby:
    file: lib/mRuby.pm
    version: 0.02
requires:
  parent: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
